### ISSUE TITLE
Option to switch between <symbol> and <g>

### ISSUE THREAD

**Issue by darsain** [w0rm/gulp-svgstore#27]
An option switch so we could choose between transforming files into `<symbol>` or `<g>`.

`<symbol>` is awesome for icons, but doesn't work for CSS backgrounds. `<g>` is awesome for CSS backgrounds.

In other words, this doesn't work with `<symbol>`, but does with `<g>`:

```css
.foo {
  background: url('images.svg#bar');
}
```
